@startuml Domain Model

hide methods 
hide stereotypes 

package "Robot" {
entity "«root» Robot" {
    <ID><VO> ID
    <VO> codigo
    <VO> nrSerie
    <VO> nickname
    <VO> marca
}
}

package "TipoRobot" {
entity "«root» TipoRobot" {
    <ID><VO> ID
    <VO> nome
    <VO> tipoTarefa
}

}

package "TipoTarefa" {
    entity "«root» TipoTarefa" {
    <ID> ID
    <VO> designação
}
}

package "Tarefa" {
entity "«root» Tarefa"  {
    <ID><VO> ID
    <VO> contacto
    <VO> tipoTarefa
    <VO> robotID
}

entity "«value object» Contacto" {
    <VO> nome
    <VO> email
    <VO> telefone
}

entity "«value object» PedidoVigilancia" {
    <ID> ID
    <VO> tarefaID
    <VO> piso
    <VO> edificio
}

entity "«value object» PedidoPickUp" {
    <ID> ID
    <VO> tarefaID
    <VO> coordenadas
}
}

package "Edificio" {
entity "«root» Edificio" {
    <ID> ID
    <VO> designacao
    <VO> nome
    <VO> dimensões
    <VO> descricao
}
}

package "Piso" {
entity "«root» Piso" {
    <ID> ID
    <VO> edificio
    <VO> descricao
}

entity Celula {
    <ID> ID
    <VO> piso
    <VO> coordenadas
    <VO> dimensao
}

entity Elevador {
    <ID> ID
    <VO> piso
    <VO> coordenadas
    <VO> edificio
}
}

package "Sala" {
entity "«root» Sala" {
    <ID> ID
    <VO> piso
    <VO> categoria
    <VO> descricao
    <VO> nome
    <VO> dimensões
}

entity Parede {
    <ID> ID
    <VO> sala
    <VO> orientacao
    <VO> dimensões
}

entity Porta {
    <ID> ID
    <VO> sala
    <VO> orientacao
    <VO> coordenadas
}


entity CategoriaSala {
    <ID> ID
    <VO> nome
    <VO> descricao
}
}

package "Passagem" {
entity "«root» Passagem" {
    <ID> ID
    <VO> edificio1
    <VO> edificio2
    <VO> piso1
    <VO> piso2
    <VO> localizacao
}
}

"«root» Robot" "n" -- "1" "«root» TipoRobot" : is of 
"«root» Robot" "1" -- "n" "«root» Tarefa" : does 
"«root» TipoRobot" "1" -- "n" "«root» TipoTarefa" : can do
"«root» Tarefa" "n" -- "1" "«root» TipoTarefa" : is of
"«root» Tarefa" "1" -- "1" "«value object» PedidoVigilancia" : can be
"«root» Tarefa" "1" -- "1" "«value object» PedidoPickUp" : can be
"«root» Tarefa" "1" -- "1" "«value object» Contacto" : has
"«root» Edificio" "1" -- "n" "«root» Piso" : has
"«root» Piso" "1" -- "n" "«root» Sala" : has 
"«root» Sala" "1" -- "n" Parede : has
"«root» Sala" "1" -- "n" Porta : has
"«root» Piso" "1" -- "n" Celula : has
"«root» Sala" "1" -- "1" CategoriaSala : is of 
"«root» Edificio" "1" -- "n" Elevador : has
"«root» Edificio" "1" -- "n" "«root» Passagem" : has 
"«root» Piso" "1" -- "n" Elevador : has
"«root» Piso" "1" -- "n" Passagem : has

@enduml
