@startuml
actor "User" as OE

activate OE
OE -> ":UI" : 1 : starts the node creation process
activate ":UI"
":UI" --> OE : 1.1 : requests data (floorCode1,floorCode2)
deactivate ":UI"
OE -> ":UI" : 2 : inserts the data (floorCode1,floorCode2)
activate ":UI"
":UI" --> OE : 2.1 : Shows data of the created passageway


deactivate ":UI"

@enduml