@startuml
actor "User" as OE

activate OE
OE -> ":UI" : 1 : starts the node creation process
activate ":UI"
":UI" --> OE : 1.1 : requests data (robot_id)
deactivate ":UI"
OE -> ":UI" : 2 : inserts the data (robot_id)
activate ":UI"
":UI" --> OE : 2.1 : shows updated robot


deactivate ":UI"

@enduml