@startuml
participant "RobDroneGo UI" as UI
participant "RobDroneGo" as API

activate UI
activate API
UI -> API : 1 : .post(/rooms)
API -> API : 1.1 : creates and saves room in database
API --> UI : 2 : response status

@enduml