@startuml
actor "User" as OE

activate OE
OE -> ":UI" : 1 : starts the node creation process
activate ":UI"
":UI" --> OE : 1.1 : requests data (buildingCode1, buildingCode2)
deactivate ":UI"
OE -> ":UI" : 2 : inserts the data (buildingCode1, buildingCode2)
activate ":UI"
":UI" --> OE : 2.1 : Shows data of the Passageways


deactivate ":UI"

@enduml