@startuml
participant "RobDroneGo UI" as UI
participant "RobDroneGo" as API

activate UI
activate API
UI -> API : 1 : .patch(/)
API -> API : 1.1 : create a map of a floor
API --> UI : 2 : response status

@enduml